language: c

before_install:
  - echo 'deb http://ftp.debian.org/debian/ wheezy-backports main' | sudo tee /etc/apt/sources.list.d/wheezy-backports.list
  - sudo apt-get update
  - sudo apt-get install luajit
  - sudo apt-get install openssl libssl-dev
  - LUAJIT=`echo /usr/bin/luajit-*`

install:
  - KEYLOGGER_MODE=X11 $LUAJIT build.lua
  - KEYLOGGER_MODE=DEV $LUAJIT build.lua
